# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Azure Pipelines
  vmimage: windows-2019
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # delete temporary git files
      dir $(System.DefaultWorkingDirectory)
      remove-item $(System.DefaultWorkingDirectory)/readme.md
      remove-item $(System.DefaultWorkingDirectory)/azure-pipelines.yml
      remove-item -recurse -force $(System.DefaultWorkingDirectory)/.git
- task: ArchiveFiles@2
  displayName: 'Archive $(System.DefaultWorkingDirectory)'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
